# Generated by Django 2.2.5 on 2019-10-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191024_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='profile_default.jpg', upload_to='profile_picture/'),
        ),
    ]
