# Generated by Django 2.2.5 on 2019-10-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_type', models.CharField(max_length=100)),
                ('blog_content', models.TextField()),
                ('pub_date', models.DateField(verbose_name='date publised')),
                ('feauture_image', models.ImageField(upload_to='feauture_images/')),
            ],
        ),
    ]
