# Generated by Django 2.2.5 on 2019-10-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191024_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='feautured_image',
            field=models.ImageField(default='media/blog-default.jpg', upload_to='feautured_images/'),
        ),
    ]
