# Generated by Django 2.2.5 on 2019-10-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191024_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateField(auto_now=True),
        ),
    ]
